### ISSUE TITLE
`exclude`

### ISSUE THREAD

**Issue by nodinosaur** [passsy/dart-lint#13]
Clarification please:
I am not sure if this package supports the `exclude` step, when testing I found that it is skipped over, i.e.

```
include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_constructors_first: true
    prefer_final_in_for_each: false

analyzer:

  exclude:
    - '**/*.chopper.dart'
    - '**/*.g.dart'
    - '**/*.*.dart' // ← I've tried using this blob pattern and all versions seem to be ignored
    - lib/**/*.g.dart // this blob pattern also appears not to work as the warning is displayed still

  errors:
    missing_required_param: error
    return_of_invalid_type_from_closure: ignore
```

I still get the following for the generated files:
```Avoid const keyword.dartunnecessary_const```

Thanks
